### ISSUE TITLE
Suggestions for someone who wants to try this project

### ISSUE THREAD

**Issue by 8lall0** [tdaede/td-crt#10]
Hi,
i have a perfect trinitron that i can "sacrifice" to test this project. How can i start with it? Is there a bom and pcbs?

Thanks!

**Comment by tdaede** [comment]
The PCBs and software needed are in this repository, however I can't currently recommend using them unless you are very familiar with the operation of a CRT. There are errors on some of them, and not all the parts work well at the moment.

**Comment by 8lall0** [comment]
@tdaede oh ok, thank you! :)
I hope this project will continue, it's so interesting.

Closing the issue :)
